### ISSUE TITLE
is there a problem with the servers?

### ISSUE THREAD

**Issue by hjgguy** [PhilippvK/playforia-minigolf#29]
i just played a multiplayer game with a friend and then tried to get back to the lobby which leads into a loading screen that woudnt finish then i tried to restart the application and then using the same host server it has another endless loading screen saying One moment please...

**Comment by PhilippvK** [comment]
Thanks for letting me know. The server should be up again in a moment.

I am sorry, but I can not afford to spend time investigating the Errors at the moment. Please just let me know if problem occurs again?

**Comment by PhilippvK** [comment]
![F7A2F2B2-2407-4516-B545-440EEBC5146E](https://user-images.githubusercontent.com/7712605/82739317-fc05e780-9d3e-11ea-96d7-5af06244489a.jpeg)

I leave this here for later investigation...

**Comment by hjgguy** [comment]
works again thank you, but i came accross another issue: track scoring doesnt work. it used to count points at the very top right of the screen, in a 4player room that was 3 points for the winner 2 points for 2 best finisher of the map if tied both second places got like 1 point each i think and whoever finished or skipped always gets 0 points.

**Comment by PhilippvK** [comment]
Thank you again for reporting. To be honest, i have not used track scoring a single time.

I will restart the server now another time to add a few debugging statements.

It seems to me like most of the issues are caused by concurrent (conflicting) actions triggered by >=2 players at the same time (vote skip, new game, leave game)

As a workaround, I recommend you make sure that there is at least one second of delay between such actions.

Also make sure do not select the trackgroups "custom" or "all" as they a broken at the moment.

**Comment by PhilippvK** [comment]
There is also another stackoverflow exception which occurs sometimes. Unfortunately I was unable to reproduce it, yet. If you managed to trigger something like that, please let me know how..

**Comment by PhilippvK** [comment]
@hjgguy Thanks for reporting. Do you have interest in looking into this by yourself? I have never used Track scoring before, so maybe it is easier for you to figure out (if you are experienced with java)

**Comment by hjgguy** [comment]
just got +32 strokes added even tho i finished first after the other 2 guys skipped (with a couple seconds apart from eachother) and none of them finishing the map. i think the game went into overflow there for me as a player, because after that i finished first in the next map and it would still give me my player turns inside the hole until it was stuck on my turn seemingly permanently.

**Comment by hjgguy** [comment]
i dont have enough experience with java but i know some people who do and could be interested in playing. also 1 guy coudnt see messages other then his own in the chat in a 3 player room while we others could see it.

**Comment by PhilippvK** [comment]
Hmmmm.

Do you think that the stability of the server got worse since the changes I applied on sunday?

Unfortunately rewriting the server side code is not an option for me. Also the used server is the the cheapest of the cheapest.

Additionally some user managed to crash the server using a targeted attack and I see a lot of of “bad word” in the usernames and lobbies.

It is great that in just over a week more than 200 players tried my server out but if this is getting out of control I have to shut it down.

**Comment by hjgguy** [comment]
hm i dont think we played enough to see whether the changes affected the stability of the server also skipping in game was always a problem leading into bugs even on the original playforia site. ddosing will always be a problem :/.
