### ISSUE TITLE
Reorganize code

### ISSUE THREAD

**Issue by pehala** [PhilippvK/playforia-minigolf#43]
The current folder structure is messy and doesn't conform to any standards.

**Comment by pehala** [comment]
There is a lot of legacy code not used in the whole project e.g. com.playray package which is not used anywhere. There are also resources which are never loaded because they are for different games and last but not least there is shared folder with resources outside client which is not used and is almost identical to the res folder inside the client. I think it would be best to delete it since it causes only confusion. To preserve it we could create a legacy branch, where we would copy master before this change. 
@PhilippvK  WDYT?

**Comment by PhilippvK** [comment]
@pehala I will create a legacy branch from the state before the Migration to maven later.

The code for the other games is useless without the server components, do feel free do remove all of that. Thank you very much for you efforts!

I think you realized how annoying it was initially to get the code running at all, the code structure as well as variable/function naming is so bad. (Party caused by the fact, that the original client.jar had to be decompiled/reverse engineered)
