### ISSUE TITLE
All tracks are missing trackSpecialSettings

### ISSUE THREAD

**Issue by Nokkasiili** [PhilippvK/playforia-minigolf#87]
Example from Darwin - Two Snakes:`S fttt12`
Description of this string can be seen here:
https://github.com/PhilippvK/playforia-minigolf/blob/85da3d2e0c9a62722ee3cd285f37c7ceaac57bee/client/src/main/java/agolf/game/GameChatPanel.java#L116

**Comment by PhilippvK** [comment]
Thanks for reporting!

Is this broken since #65 or was this never working in this repo?

**Comment by Nokkasiili** [comment]
Not sure but they are in old repo
https://github.com/WorldStarHipHopX/playforia/blob/7a7e573a1688bf62f465173153f4936b27430be5/tracks/modern/Darwin-_sgard.track#L5

**Comment by PhilippvK** [comment]
@pehala Any opinion?

**Comment by PhilippvK** [comment]
The `S` Row was not documented in https://github.com/PhilippvK/playforia-minigolf/blob/master/doc/FileFormat.md as far as I can tell.

**Comment by Nokkasiili** [comment]
#88

**Comment by Nokkasiili** [comment]
needs also be implemented here
https://github.com/PhilippvK/playforia-minigolf/blob/master/shared/src/main/java/org/moparforia/shared/tracks/Track.java

**Comment by pehala** [comment]
Thanks for the report. It indeed looks like it is missing from my new implementation as it wasn't properly documented, is it an optional row or a mandatory one? 

As you correctly point out the S row need to be implemented in all kinds of different places, since Track will be changed. 

@Nokkasiili Would you like to try to add that to your PR or should I edit it? Since tracks are now covered by tests you should get a good idea if the new implementation is correct from them and compile errors combined.

**Comment by Nokkasiili** [comment]
`    protected String getTrackSettings() {
        return this.trackSettings.equals("fttt14") ? null : this.trackSettings;
    }
`
Client will use default value if its missing
