### ISSUE TITLE
Set an own Nickname

### ISSUE THREAD

**Issue by eYeWoRRy** [PhilippvK/playforia-minigolf#9]
It would be great to change the login screen to a free nickname without a password 🤔

**Comment by PhilippvK** [comment]
Yeah this would be great to get rid of the guest usernames.

This will probably rather hard and as I do not understand the launcher completely I am not sure if it can figure it out.

So help ist greatly appreciated.

**Comment by PhilippvK** [comment]
Done in 6c2eed3a5324aaaac914f92cf143b6b8acf3156a.

Just type in your nick in the username filed. Leave it empty to be anonymous.

Warning: There is no error checking and so on....

**Comment by eYeWoRRy** [comment]
I changed the Login Screen on client side too - but I cannot push the changes :-/

**Comment by marecabo** [comment]
@eYeWoRRy
It looks like, you have not created a fork (personal copy) of this repository. With the usual workflow on GitHub, you would commit and push your changes to a new branch of your fork first and then create a pull request to this repository on the GitHub website. (There will be a button for creating a pull request once your fork has changes the original repository does not have.)

Only if the owner of this repository sets you as a collaborator, you can directly push commits to his repository.

If I'm telling you things you already know, please ignore what I wrote. Otherwise, always feel free to ask for more details or help.

**Comment by PhilippvK** [comment]
Exactly!

As you probably already have commited your changes locally, once you have created your fork, adding a second remote might make your life easier:

```
git remote add github https://github.com/USERNAME/playforia-minigolf.git
git fetch github
git push github BRANCH
```

As already mentioned, move your new commits to a feature branch `git checkout -b feature-loginscreen` before.

**Comment by eYeWoRRy** [comment]
Hy guys. Thx for your feedback.
I hope I did it correct - pull request is out.
